<a href="https://colab.research.google.com/github/SanskrutiPanda/18CSE103/blob/main/DMDW_ASSIGNMENT_2_18CSE103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Download a dataset from kaggle and upload it in jupyter
notebook or google colab. Perform any random operation on
the dataset.**. 

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Bank_churn_modelling.csv to Bank_churn_modelling.csv


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("Bank_churn_modelling.csv")

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.describe()

RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

In [ ]:
df.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
df.duplicated().sum()

0

**Practice 10 python programs using numpy libraries**

In [ ]:
#1)Create NumPy Array
import numpy as np
 
array1d = np.array([1, 2, 3, 4, 5, 6])
array2d = np.array([[1, 2, 3], [4, 5, 6]])
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
 
print(array1d)
 
print("-" * 10)
print(array2d)
 
print("-" * 10)
print(array3d)

[1 2 3 4 5 6]
----------
[[1 2 3]
 [4 5 6]]
----------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#2)Data Types
import numpy as np
type1 = np.array([1, 2, 3, 4, 5, 6])
type2 = np.array([1.5, 2.5, 0.5, 6])
type3 = np.array(['a', 'b', 'c'])
type4 = np.array(["Canada", "Australia"], dtype='U5')
type5 = np.array([555, 666], dtype=float)
print(type1.dtype)
print(type2.dtype)
print(type3.dtype)
print(type4.dtype)
print(type5.dtype)
 
print(type4)

int64
float64
<U1
<U5
float64
['Canad' 'Austr']


In [ ]:
#3)Shape of an array
import numpy as np
 
array1d = np.array([1, 2, 3, 4, 5, 6])
array2d = np.array([[1, 2, 3], [4, 5, 6]])
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
 
print(array1d.shape)
print(array2d.shape)
print(array3d.shape)

(6,)
(2, 3)
(2, 2, 3)


In [ ]:
#4)Reshape an array
import numpy as np
 
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray = thearray.reshape(2, 4)
print(thearray)
 
print("-" * 10)
thearray = thearray.reshape(4, 2)
print(thearray)
 
print("-" * 10)
thearray = thearray.reshape(8, 1)
print(thearray)

[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
#5)Resize an array
import numpy as np
 
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(2, 4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(3, 3)
print(thearray)

[1 2 3 4]
----------
[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [ ]:
#6)Transform List or Tuple into NumPy array
import numpy as np
 
thelist = [1, 2, 3]
print(type(thelist))  # <class 'list'>
 
array1 = np.array(thelist)
print(type(array1))  # <class 'numpy.ndarray'>
 
 
thetuple = ((1, 2, 3))
print(type(thetuple))  # <class 'tuple'>
 
array2 = np.array(thetuple)
print(type(array2))  # <class 'numpy.ndarray'>
 
array3 = np.array([thetuple, thelist, array1])
print(array3)

<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
#7)zero array
import numpy as np
 
array1d = np.zeros(3)
print(array1d)
 
array2d = np.zeros((2, 4))
print(array2d)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#8)Mean
import numpy as np
 
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print("Mean: ", np.mean(array1))

Mean:  35.0


In [ ]:
#9)Standard deviation 
import numpy as np
 
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print("Std: ", np.std(array1))

Std:  17.07825127659933


In [ ]:
#10)sum
import numpy as np
 
array1 = np.array([[10, 20, 30], [40, 50, 60]])
print("Sum: ", np.sum(array1))

Sum:  210


**Practice 10 python programs using pandas libraries.**

In [ ]:
#1)Creating Series using list:

import pandas as pd
 
ser1 = pd.Series([1.5, 2.5, 3, 4.5, 5.0, 6])
print(ser1)

0    1.5
1    2.5
2    3.0
3    4.5
4    5.0
5    6.0
dtype: float64


In [ ]:
#2)to get index and values of series in Pandas
import pandas as pd
 
ser1 = pd.Series({"India": "New Delhi",
                  "Japan": "Tokyo",
                  "UK": "London"})
 
print(ser1.values)
print(ser1.index)

['New Delhi' 'Tokyo' 'London']
Index(['India', 'Japan', 'UK'], dtype='object')


In [ ]:
#3)Get Length Size and Shape of a Series:
import pandas as pd
 
values = ["India", "Canada", "Australia",
          "Japan", "Germany", "France"]
 
code = ["IND", "CAN", "AUS", "JAP", "GER", "FRA"]
 
ser1 = pd.Series(values, index=code)
 
print(len(ser1))
 
print(ser1.shape)
 
print(ser1.size)

6
(6,)
6


In [ ]:
#4)to get the first or last few rows from a Series in Pandas
import pandas as pd
 
values = ["India", "Canada", "Australia",
          "Japan", "Germany", "France"]
 
code = ["IND", "CAN", "AUS", "JAP", "GER", "FRA"]
 
ser1 = pd.Series(values, index=code)
 
print("-----Head()-----")
print(ser1.head())
 
print("\n\n-----Head(2)-----")
print(ser1.head(2))

-----Head()-----
IND        India
CAN       Canada
AUS    Australia
JAP        Japan
GER      Germany
dtype: object


-----Head(2)-----
IND     India
CAN    Canada
dtype: object


In [ ]:
#5)Slicing a Series into subsets in Pandas
import pandas as pd
 
num = [000, 100, 200, 300, 400, 500, 600, 700, 800, 900]
 
idx = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
 
series = pd.Series(num, index=idx)
 
print("\n [2:2] \n")
print(series[2:4])
 
print("\n [1:6:2] \n")
print(series[1:6:2])
 


 [2:2] 

C    200
D    300
dtype: int64

 [1:6:2] 

B    100
D    300
F    500
dtype: int64


In [ ]:
#6)to create and print DataFrame in pandas

import pandas as pd
 
employees = pd.DataFrame({
    'EmpCode': ['Emp001', 'Emp00'],
    'Name': ['John Doe', 'William Spark'],
    'Occupation': ['Chemist', 'Statistician'],
    'Date Of Join': ['2018-01-25', '2018-01-26'],
    'Age': [23, 24]})
 
print(employees)


  EmpCode           Name    Occupation Date Of Join  Age
0  Emp001       John Doe       Chemist   2018-01-25   23
1   Emp00  William Spark  Statistician   2018-01-26   24


In [ ]:
#7)to set Index and Columns in Pandas DataFrame

import pandas as pd
 
employees = pd.DataFrame(
    data={'Name': ['John Doe', 'William Spark'],
          'Occupation': ['Chemist', 'Statistician'],
          'Date Of Join': ['2018-01-25', '2018-01-26'],
          'Age': [23, 24]},
    index=['Emp001', 'Emp002'],
    columns=['Name', 'Occupation', 'Date Of Join', 'Age'])
 
print(employees)

                 Name    Occupation Date Of Join  Age
Emp001       John Doe       Chemist   2018-01-25   23
Emp002  William Spark  Statistician   2018-01-26   24


In [ ]:
#8)to rename DataFrame columns name in pandas

import pandas as pd
 
employees = pd.DataFrame({
    'EmpCode': ['Emp001', 'Emp00'],
    'Name': ['John Doe', 'William Spark'],
    'Occupation': ['Chemist', 'Statistician'],
    'Date Of Join': ['2018-01-25', '2018-01-26'],
    'Age': [23, 24]})
 
employees.columns = ['EmpCode', 'EmpName', 'EmpOccupation', 'EmpDOJ', 'EmpAge']
 
print(employees)

  EmpCode        EmpName EmpOccupation      EmpDOJ  EmpAge
0  Emp001       John Doe       Chemist  2018-01-25      23
1   Emp00  William Spark  Statistician  2018-01-26      24


In [ ]:
#9)Adding new column to existing DataFrame in Pandas

import pandas as pd
 
employees = pd.DataFrame({
    'EmpCode': ['Emp001', 'Emp002', 'Emp003', 'Emp004', 'Emp005'],
    'Name': ['John', 'Doe', 'William', 'Spark', 'Mark'],
    'Occupation': ['Chemist', 'Statistician', 'Statistician',
                   'Statistician', 'Programmer'],
    'Date Of Join': ['2018-01-25', '2018-01-26', '2018-01-26', '2018-02-26',
                     '2018-03-16'],
    'Age': [23, 24, 34, 29, 40]})
 
employees['City'] = ['London', 'Tokyo', 'Sydney', 'London', 'Toronto']
 
print(employees)

  EmpCode     Name    Occupation Date Of Join  Age     City
0  Emp001     John       Chemist   2018-01-25   23   London
1  Emp002      Doe  Statistician   2018-01-26   24    Tokyo
2  Emp003  William  Statistician   2018-01-26   34   Sydney
3  Emp004    Spark  Statistician   2018-02-26   29   London
4  Emp005     Mark    Programmer   2018-03-16   40  Toronto


In [ ]:
#10)to get a list of the column headers from a Pandas DataFrame
import pandas as pd
 
employees = pd.DataFrame({
    'EmpCode': ['Emp001', 'Emp002', 'Emp003', 'Emp004', 'Emp005'],
    'Name': ['John', 'Doe', 'William', 'Spark', 'Mark'],
    'Occupation': ['Chemist', 'Statistician', 'Statistician',
                   'Statistician', 'Programmer'],
    'Date Of Join': ['2018-01-25', '2018-01-26', '2018-01-26', '2018-02-26',
                     '2018-03-16'],
    'Age': [23, 24, 34, 29, 40]})
 
print(list(employees))
 
print(list(employees.columns.values))
 
print(employees.columns.tolist())

['EmpCode', 'Name', 'Occupation', 'Date Of Join', 'Age']
['EmpCode', 'Name', 'Occupation', 'Date Of Join', 'Age']
['EmpCode', 'Name', 'Occupation', 'Date Of Join', 'Age']
